# .goreleaser.yaml
version: 2
project_name: fce

before:
  hooks:
    - go mod tidy

builds:
  - id: fce
    binary: fce
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: fce
    format: tar.gz
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - name: fce
    repository:
      owner: DishIs
      name: homebrew-tap
    homepage: "https://github.com/DishIs/fce-cli"
    description: "FreeCustom.Email CLI — Manage disposable inboxes from your terminal."
    install: |
      bin.install "fce"

scoops:
  - name: fce
    repository:
      owner: DishIs
      name: scoop-bucket
    homepage: "https://github.com/DishIs/fce-cli"
    description: "FreeCustom.Email CLI — Manage disposable inboxes from your terminal."
    license: MIT

chocolateys:
  - name: fce
    owners: DishIs
    authors: DishIs
    project_url: "https://github.com/DishIs/fce-cli"
    description: "FreeCustom.Email CLI — Manage disposable inboxes from your terminal."
    summary: "FreeCustom.Email CLI"
    # api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
